### ISSUE TITLE
filtros - página de libros

### ISSUE THREAD

**Issue by AnderMendoza** [AnderMendoza/Stose#30]
-Adaptar los espacios para la inserción de cada categoría.
-Colocar chechbox para filtrar la búsqueda de los productos.
-Colocar una escala de precio que funcione como filtro.

**Comment by yeshua-aguilar** [comment]
-Adaptar los espacios para colocar las tarjetas.
-Insertar el espacio para la inserción de imágenes.
-Debajo de cada imagen colocar una breve descripción.
