### ISSUE TITLE
Cobertura sobre lo planificado - testing

### ISSUE THREAD

**Issue by AnderMendoza** [AnderMendoza/Stose#91]
- Planificar la realización de pruebas al código
-- Elegir las herramientas a utilizar
-- Realizar pruebas funcionales y no funcionales

- Documentar la planificación de las pruebas
-- Detallar cada una de las pruebas, sus estrategias, aplicaciones a usar e integrantes encargados de cada una de ellas

**Comment by yeshua-aguilar** [comment]
prueba de rendimiento de la web:

Se han llenado los cuadros cone stos datos, se le han inviaron 100 que por cada uno pase 5 segundos y que lo repita durantes 100 veces

![Image](https://user-images.githubusercontent.com/81573986/198850039-73753269-3e9f-4aba-87ac-ea687f6ec05b.png)

los resultados indican que la web sorporta que le envien 100 veces de 100 usuarios. Con un rendimiento de carga maximo de un 1 segundo

![Image](https://user-images.githubusercontent.com/81573986/198850109-ef8a723c-9384-4ea9-b20c-0f93325d68e4.png)

pero en encambio si se le envia mas de 5000 usuario de un solo tiron la web no soporta

nota: no he podido tomar captura de ese escenario porque al hacer mas de 5000 usuario y terminara la prueba con. mi CPU llego al 100% y me dio la pantalla azul de la muerte, Pero yo soy testigo que no soporto.

**Comment by AnderMendoza** [comment]
> prueba de rendimiento de la web:
> 
> Se han llenado los cuadros con estos datos, se le han inviaron 100 que por cada uno pase 5 segundos...

JAJAJAJA pobre PC 😅 pero por los demás buen aporte 👍

**Comment by Jankarurosu** [comment]
Se realizo un informe sobre la planificación de las pruebas que contiene información sobre herramientas, pruebas y funcionalidades que se podrían llegar a poner a prueba.

Enlace del word: 
https://docs.google.com/document/d/12Xkf_G_Iq0y8Jp4UDTfDOr1aHiGmQeqLWV8qMXiX7t0/edit?usp=sharing
